"""Prescription PDF rendering with ReportLab (Platypus).

Platypus flows text and tables automatically, so long medication lists wrap
and paginate instead of running off the page as fixed canvas coordinates did.

Security: Platypus `Paragraph` parses a mini-markup language, so every
user-supplied string goes through `_esc` first. A patient named
"<font size=40>x" is printed literally, not interpreted.
"""

import io
from datetime import datetime, timezone
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import HRFlowable, KeepTogether, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


INK = colors.HexColor("#0f172a")
MUTED = colors.HexColor("#64748b")
BRAND = colors.HexColor("#0f766e")
RULE = colors.HexColor("#e2e8f0")
SOFT = colors.HexColor("#f1f5f9")

APPOINTMENT_TYPE_LABELS = {
    "regular_checkup": "Regular check-up",
    "follow_up": "Follow-up",
    "consultation": "Consultation",
    "emergency": "Emergency",
}

FOOTER_DISCLAIMER = (
    "Generated by AI-CLINIC, an educational demonstration system. "
    "Not a valid medical prescription."
)


def _esc(value) -> str:
    return escape(str(value)) if value not in (None, "") else "—"


def _styles():
    base = getSampleStyleSheet()
    return {
        "clinic": ParagraphStyle("clinic", parent=base["Title"], fontSize=17, leading=21, alignment=0, textColor=INK, spaceAfter=0),
        "muted": ParagraphStyle("muted", parent=base["Normal"], fontSize=8.5, leading=11, textColor=MUTED),
        "doc_title": ParagraphStyle("doc_title", parent=base["Normal"], fontName="Helvetica-Bold", fontSize=12, textColor=BRAND, alignment=TA_RIGHT),
        "right": ParagraphStyle("right", parent=base["Normal"], fontSize=8.5, leading=11, textColor=MUTED, alignment=TA_RIGHT),
        "section": ParagraphStyle("section", parent=base["Normal"], fontName="Helvetica-Bold", fontSize=8.5, textColor=MUTED, spaceBefore=12, spaceAfter=4),
        "label": ParagraphStyle("label", parent=base["Normal"], fontSize=7.5, leading=9, textColor=MUTED),
        "value": ParagraphStyle("value", parent=base["Normal"], fontSize=10, leading=13, textColor=INK),
        "body": ParagraphStyle("body", parent=base["Normal"], fontSize=10, leading=14, textColor=INK),
        "cell_head": ParagraphStyle("cell_head", parent=base["Normal"], fontName="Helvetica-Bold", fontSize=8.5, textColor=MUTED),
        "cell": ParagraphStyle("cell", parent=base["Normal"], fontSize=9.5, leading=12.5, textColor=INK),
        "note": ParagraphStyle("note", parent=base["Normal"], fontSize=8.5, leading=11.5, textColor=MUTED),
    }


def _info_block(label: str, rows: list[tuple[str, str]], s) -> list:
    items = [Paragraph(label.upper(), s["section"])]
    for key, value in rows:
        items.append(Paragraph(key, s["label"]))
        items.append(Paragraph(_esc(value), s["value"]))
        items.append(Spacer(1, 3))
    return items


def build_prescription_pdf(
    prescription: dict, appointment: dict, patient: dict, doctor: dict | None, clinic_name: str, clinic_address: str
) -> bytes:
    """Render one prescription. Arguments are the raw MongoDB documents."""
    s = _styles()
    rx_id = prescription["_id"]
    doctor_name = doctor["full_name"] if doctor else ""
    issued = prescription["created_at"]
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=22 * mm,
        title=f"Prescription RX-{rx_id:06d}",
        author=clinic_name,
    )
    width = doc.width - 12  # the page frame has 6pt padding on each side
    story = []

    # Header: clinic on the left, document id on the right.
    header = Table(
        [[
            [Paragraph(_esc(clinic_name), s["clinic"]), Paragraph(_esc(clinic_address), s["muted"])],
            [
                Paragraph("PRESCRIPTION", s["doc_title"]),
                Paragraph(f"No. RX-{rx_id:06d}", s["right"]),
                Paragraph(f"Issued {issued:%d %b %Y, %H:%M} UTC", s["right"]),
            ],
        ]],
        colWidths=[width * 0.62, width * 0.38],
    )
    header.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 0), ("RIGHTPADDING", (0, 0), (-1, -1), 0)]))
    story += [header, Spacer(1, 6), HRFlowable(width="100%", thickness=1.2, color=BRAND), Spacer(1, 2)]

    # Patient / appointment / prescriber.
    info = Table(
        [[
            _info_block("Patient", [("Name", patient["full_name"]), ("Phone", patient["phone"]), ("Patient ID", f"P-{patient['_id']:05d}")], s),
            _info_block(
                "Appointment",
                [
                    ("Date", appointment["scheduled_at"].strftime("%d %b %Y, %H:%M")),
                    ("Type", APPOINTMENT_TYPE_LABELS.get(appointment["appointment_type"], appointment["appointment_type"])),
                    ("Appointment ID", f"A-{appointment['_id']:05d}"),
                ],
                s,
            ),
            _info_block("Prescriber", [("Name", doctor_name or "—"), ("Role", "Physician")], s),
        ]],
        colWidths=[width / 3] * 3,
    )
    info.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 0)]))
    story += [info, HRFlowable(width="100%", thickness=0.6, color=RULE)]

    # Clinician-authored content.
    story += [Paragraph("DIAGNOSIS", s["section"]), Paragraph(_esc(prescription["diagnosis"]), s["body"])]

    rows = [[Paragraph(h, s["cell_head"]) for h in ("#", "Medication", "Dosage", "Instructions")]]
    for i, med in enumerate(prescription.get("medications") or [], start=1):
        rows.append([
            Paragraph(str(i), s["cell"]),
            Paragraph(f"<b>{_esc(med.get('name'))}</b>", s["cell"]),
            Paragraph(_esc(med.get("dosage")), s["cell"]),
            Paragraph(_esc(med.get("instructions")), s["cell"]),
        ])
    meds = Table(rows, colWidths=[width * 0.06, width * 0.32, width * 0.22, width * 0.40], repeatRows=1)
    meds.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), SOFT),
        ("LINEBELOW", (0, 0), (-1, -1), 0.5, RULE),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story += [Paragraph("MEDICATIONS &amp; INSTRUCTIONS", s["section"]), meds]

    if prescription.get("notes"):
        story += [Paragraph("CLINICIAN NOTES", s["section"]), Paragraph(_esc(prescription["notes"]).replace("\n", "<br/>"), s["body"])]

    signature = Table(
        [[Paragraph("", s["body"]), Paragraph(f"{_esc(doctor_name)}<br/><font color='#64748b' size='8'>Prescribing clinician — signature</font>", s["body"])]],
        colWidths=[width * 0.55, width * 0.45],
    )
    signature.setStyle(TableStyle([("LINEABOVE", (1, 0), (1, 0), 0.8, INK), ("TOPPADDING", (0, 0), (-1, -1), 4), ("LEFTPADDING", (0, 0), (-1, -1), 0)]))
    story += [Spacer(1, 28), KeepTogether(signature)]

    # AI decision-support note, visually and textually separate from the prescription.
    prediction = appointment.get("prediction") or {}
    if prediction.get("status") == "ok":
        text = (
            "<b>Decision-support note — not part of this prescription.</b> At intake, the AI-CLINIC "
            f"model (version {_esc(prediction.get('model_version'))}) suggested "
            f"<b>{_esc(prediction['predicted_disease'])}</b> with a model confidence of "
            f"{prediction['confidence']:.0%} (the share of decision trees in agreement, not a clinical "
            "probability). The diagnosis and medications above were written by the prescribing clinician."
        )
        box = Table([[Paragraph(text, s["note"])]], colWidths=[width])
        box.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), SOFT), ("BOX", (0, 0), (-1, -1), 0.5, RULE), ("LEFTPADDING", (0, 0), (-1, -1), 8), ("RIGHTPADDING", (0, 0), (-1, -1), 8), ("TOPPADDING", (0, 0), (-1, -1), 6), ("BOTTOMPADDING", (0, 0), (-1, -1), 6)]))
        story += [Spacer(1, 22), KeepTogether(box)]

    def footer(canvas, document):
        canvas.saveState()
        canvas.setStrokeColor(RULE)
        canvas.line(document.leftMargin, 15 * mm, document.leftMargin + document.width, 15 * mm)
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(MUTED)
        canvas.drawString(document.leftMargin, 10.5 * mm, FOOTER_DISCLAIMER)
        canvas.drawRightString(
            document.leftMargin + document.width, 10.5 * mm, f"Generated {generated_at}  ·  Page {document.page}"
        )
        canvas.restoreState()

    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    return buffer.getvalue()
