from sqlalchemy import JSON, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from ..extensions import db
from .base import TimestampMixin, iso


class Prescription(TimestampMixin, db.Model):
    """A prescription written by a doctor. Never generated by the model.

    `medications` is a list of {"name", "dosage", "instructions"} objects.
    """

    __tablename__ = "prescriptions"

    id: Mapped[int] = mapped_column(primary_key=True)
    appointment_id: Mapped[int] = mapped_column(ForeignKey("appointments.id"), index=True)
    doctor_id: Mapped[int] = mapped_column(ForeignKey("users.id"))
    diagnosis: Mapped[str] = mapped_column(String(200))
    medications: Mapped[list] = mapped_column(JSON, default=list)
    notes: Mapped[str | None] = mapped_column(Text)

    appointment = relationship("Appointment", back_populates="prescriptions")
    doctor = relationship("User")

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "appointment_id": self.appointment_id,
            "doctor": self.doctor.to_dict() if self.doctor else None,
            "diagnosis": self.diagnosis,
            "medications": self.medications or [],
            "notes": self.notes,
            "created_at": iso(self.created_at),
        }
